services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${USER_PASSWD}
    ports:
      - ${DB_PORT}:3306
  db-dashboard:
    image: adminer
    ports:
      - 8080:8080
